### ISSUE TITLE
Entering properties when creating a new Execution zone results in "Internal Server Error"

### ISSUE THREAD

**Issue by M4nuF** [hybris/zenboot#29]
How to repdroduce this error:
- Create new execution zone
- In the mask add one or more properties
- Click save

This will result in an "Internal Server Error" (500)

**Comment by mstadelm** [comment]
Happened because the ExecutionZone domain object execute an update on the accessCache while save progress. Fixed with this commit: https://github.com/hybris/zenboot/commit/28f39c882aadb30dcf9fb7ee496bef467fccc9aa
